# Generated by Codex on 2026-05-24

import uuid_utils.compat
from django.db import migrations, models


CREATE_CHAT_USER_PLATFORM_SOURCE = """
CREATE TABLE IF NOT EXISTS public.chat_user_platform_source (
    id uuid NOT NULL PRIMARY KEY,
    auth_type varchar(20) NOT NULL UNIQUE,
    config jsonb NOT NULL,
    type varchar(20) NOT NULL,
    is_active boolean NOT NULL,
    is_valid boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_auth_type_88e98d59_like
    ON public.chat_user_platform_source (auth_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_type_8cfc5c40
    ON public.chat_user_platform_source (type);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_type_8cfc5c40_like
    ON public.chat_user_platform_source (type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_is_active_5814729d
    ON public.chat_user_platform_source (is_active);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_is_valid_62fa8d03
    ON public.chat_user_platform_source (is_valid);
"""

DROP_CHAT_USER_PLATFORM_SOURCE = """
DROP TABLE IF EXISTS public.chat_user_platform_source;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0005_resourcemapping"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_CHAT_USER_PLATFORM_SOURCE,
                    reverse_sql=DROP_CHAT_USER_PLATFORM_SOURCE,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ChatUserAuth",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid_utils.compat.uuid7,
                                editable=False,
                                max_length=128,
                                primary_key=True,
                                serialize=False,
                                verbose_name="主键id",
                            ),
                        ),
                        (
                            "auth_type",
                            models.CharField(db_index=True, max_length=20, unique=True, verbose_name="认证类型"),
                        ),
                        ("config", models.JSONField(default=dict, verbose_name="认证配置")),
                        ("type", models.CharField(db_index=True, default="SSO", max_length=20, verbose_name="类型")),
                        ("is_active", models.BooleanField(db_index=True, default=False, verbose_name="是否启用")),
                        ("is_valid", models.BooleanField(db_index=True, default=False, verbose_name="是否有效")),
                    ],
                    options={
                        "db_table": "chat_user_platform_source",
                    },
                ),
            ],
        ),
    ]
