# Generated by Codex on 2026-05-24

from django.db import migrations


ENSURE_CHAT_USER_PLATFORM_SOURCE = """
CREATE TABLE IF NOT EXISTS public.chat_user_platform_source (
    id uuid NOT NULL PRIMARY KEY,
    auth_type varchar(20) NOT NULL UNIQUE,
    config jsonb NOT NULL,
    type varchar(20) NOT NULL,
    is_active boolean NOT NULL,
    is_valid boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_auth_type_88e98d59_like
    ON public.chat_user_platform_source (auth_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_type_8cfc5c40
    ON public.chat_user_platform_source (type);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_type_8cfc5c40_like
    ON public.chat_user_platform_source (type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_is_active_5814729d
    ON public.chat_user_platform_source (is_active);
CREATE INDEX IF NOT EXISTS chat_user_platform_source_is_valid_62fa8d03
    ON public.chat_user_platform_source (is_valid);

DO $$
BEGIN
    IF to_regclass('public.chat_user_auth') IS NOT NULL THEN
        INSERT INTO public.chat_user_platform_source (id, auth_type, config, type, is_active, is_valid)
        SELECT id, auth_type, config, type, is_active, is_valid
        FROM public.chat_user_auth
        ON CONFLICT (auth_type) DO UPDATE SET
            config = EXCLUDED.config,
            type = EXCLUDED.type,
            is_active = EXCLUDED.is_active,
            is_valid = EXCLUDED.is_valid;
    END IF;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0006_chatuserauth"),
    ]

    operations = [
        migrations.RunSQL(sql=ENSURE_CHAT_USER_PLATFORM_SOURCE, reverse_sql=migrations.RunSQL.noop),
    ]
