# Generated by Codex on 2026-05-24

import uuid_utils.compat
from django.db import migrations, models


CREATE_PLATFORM_SOURCE = """
CREATE TABLE IF NOT EXISTS public.platform_source (
    create_time timestamp with time zone NOT NULL,
    update_time timestamp with time zone NOT NULL,
    id uuid NOT NULL PRIMARY KEY,
    auth_type varchar(20) NOT NULL UNIQUE,
    config jsonb NOT NULL,
    type varchar(20) NOT NULL,
    is_active boolean NOT NULL,
    is_valid boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS platform_source_auth_type_like
    ON public.platform_source (auth_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS platform_source_type_idx
    ON public.platform_source (type);
CREATE INDEX IF NOT EXISTS platform_source_type_like
    ON public.platform_source (type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS platform_source_is_active_idx
    ON public.platform_source (is_active);
CREATE INDEX IF NOT EXISTS platform_source_is_valid_idx
    ON public.platform_source (is_valid);
CREATE INDEX IF NOT EXISTS platform_source_create_time_idx
    ON public.platform_source (create_time);
CREATE INDEX IF NOT EXISTS platform_source_update_time_idx
    ON public.platform_source (update_time);
"""

DROP_PLATFORM_SOURCE = """
DROP TABLE IF EXISTS public.platform_source;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0007_ensure_chat_user_platform_source"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=CREATE_PLATFORM_SOURCE, reverse_sql=DROP_PLATFORM_SOURCE),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PlatformSourceAuth",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid_utils.compat.uuid7,
                                editable=False,
                                max_length=128,
                                primary_key=True,
                                serialize=False,
                                verbose_name="涓婚敭id",
                            ),
                        ),
                        (
                            "auth_type",
                            models.CharField(db_index=True, max_length=20, unique=True, verbose_name="璁よ瘉绫诲瀷"),
                        ),
                        ("config", models.JSONField(default=dict, verbose_name="璁よ瘉閰嶇疆")),
                        ("type", models.CharField(db_index=True, default="SSO", max_length=20, verbose_name="绫诲瀷")),
                        ("is_active", models.BooleanField(db_index=True, default=False, verbose_name="鏄惁鍚敤")),
                        ("is_valid", models.BooleanField(db_index=True, default=False, verbose_name="鏄惁鏈夋晥")),
                        (
                            "create_time",
                            models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="鍒涘缓鏃堕棿"),
                        ),
                        (
                            "update_time",
                            models.DateTimeField(auto_now=True, db_index=True, verbose_name="淇敼鏃堕棿"),
                        ),
                    ],
                    options={
                        "db_table": "platform_source",
                    },
                ),
                migrations.AlterField(
                    model_name="systemsetting",
                    name="type",
                    field=models.IntegerField(
                        choices=[
                            (0, "閭"),
                            (1, "绉侀挜绉橀挜"),
                            (2, "鏃ュ織娓呯悊鏃堕棿"),
                            (3, "Login Auth"),
                        ],
                        default=0,
                        primary_key=True,
                        serialize=False,
                        verbose_name="璁剧疆绫诲瀷",
                    ),
                ),
            ],
        ),
    ]
