# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0008_platformsourceauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "邮箱"),
                    (1, "私钥秘钥"),
                    (2, "日志清理时间"),
                    (3, "Login Auth"),
                ],
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="设置类型",
            ),
        ),
    ]
